exclude_paths:
  - tmp
  - vendor

detectors:
  DuplicateMethodCall:
    exclude:
      - "Marameters::Builder#call"
      - "Marameters::Categorizer#filter"
  LongParameterList:
    enabled: false
  NilCheck:
    exclude:
      - "Marameters::Defaulter#call"
  RepeatedConditional:
    exclude:
      - "Marameters::Categorizer"
  TooManyMethods:
    exclude:
      - "Marameters::Probe"
  TooManyStatements:
    exclude:
      - "Marameters::Builder#call"

directories:
  "spec/support/shared_contexts":
    LongParameterList:
      enabled: false
