exclude_paths:
  - tmp
  - vendor

detectors:
  DuplicateMethodCall:
    exclude:
      - "Marameters::Categorizer#filter"
      - "Marameters::Signatures::Builder#call"
      - "Marameters::Signatures::Inheritor#merge"
      - "Marameters::Signatures::Super#merge"
  FeatureEnvy:
    exclude:
      - "Marameters::Signatures::Inheritor#merge"
      - "Marameters::Signatures::Super#merge"
  LongParameterList:
    enabled: false
  NestedIterators:
    exclude:
      - "Marameters::Signatures::Super#merge"
  RepeatedConditional:
    exclude:
      - "Marameters::Categorizer"
  TooManyMethods:
    exclude:
      - "Marameters::Probe"
  TooManyStatements:
    exclude:
      - "Marameters::Signatures::Builder#call"
      - "Marameters::Signatures::Inheritor#merge"
      - "Marameters::Signatures::Super#merge"

directories:
  "spec/support/shared_contexts":
    LongParameterList:
      enabled: false
