exclude_paths:
  - tmp
  - vendor

detectors:
  NilCheck:
    exclude:
      - "Marameters::Defaulter#call"

  TooManyMethods:
    exclude:
      - "Marameters::Probe"
  TooManyStatements:
    exclude:
      - "Marameters::Builder#call"

directories:
  "spec/support/shared_contexts":
    LongParameterList:
      enabled: false
