exclude_paths:
  - tmp
  - vendor

detectors:
  TooManyMethods:
    exclude:
      - "Marameters::Analyzer"

directories:
  "spec/support/shared_contexts":
    LongParameterList:
      enabled: false
