inherit_gem:
  caliber: config/all.yml

Lint/UselessMethodDefinition:
  Exclude:
    - "spec/lib/marameters/*"
Metrics/AbcSize:
  Exclude:
    - "lib/marameters/categorizer.rb"
    - "lib/marameters/signatures/inheritor.rb"
Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/marameters/categorizer.rb"
    - "lib/marameters/signatures/builder.rb"
    - "lib/marameters/signatures/inheritor.rb"
Metrics/MethodLength:
  Exclude:
    - "lib/marameters/categorizer.rb"
    - "lib/marameters/signatures/builder.rb"
    - "lib/marameters/signatures/inheritor.rb"
Metrics/ParameterLists:
  Exclude:
    - "spec/support/shared_contexts/parameters.rb"
Metrics/PerceivedComplexity:
  Exclude:
    - "lib/marameters/categorizer.rb"
